In [6]:
import pandas as pd

import numpy as np

import matplotlib.pyplot as plt

df=pd.read_csv("data/Titanic-Dataset.csv")

df.head()        


,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S


In [7]:
df.tail()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.00,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.00,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.45,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.00,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.75,NaN,Q


In [8]:
ages = df['Age'].dropna().to_numpy()
print(ages)

[22.   38.   26.   35.   35.   54.    2.   27.   14.    4.   58.   20.
 39.   14.   55.    2.   31.   35.   34.   15.   28.    8.   38.   19.
 40.   66.   28.   42.   21.   18.   14.   40.   27.    3.   19.   18.
  7.   21.   49.   29.   65.   21.   28.5   5.   11.   22.   38.   45.
  4.   29.   19.   17.   26.   32.   16.   21.   26.   32.   25.    0.83
 30.   22.   29.   28.   17.   33.   16.   23.   24.   29.   20.   46.
 26.   59.   71.   23.   34.   34.   28.   21.   33.   37.   28.   21.
 38.   47.   14.5  22.   20.   17.   21.   70.5  29.   24.    2.   21.
 32.5  32.5  54.   12.   24.   45.   33.   20.   47.   29.   25.   23.
 19.   37.   16.   24.   22.   24.   19.   18.   19.   27.    9.   36.5
 42.   51.   22.   55.5  40.5  51.   16.   30.   44.   40.   26.   17.
  1.    9.   45.   28.   61.    4.    1.   21.   56.   18.   50.   30.
 36.    9.    1.    4.   45.   40.   36.   32.   19.   19.    3.   44.
 58.   42.   24.   28.   34.   45.5  18.    2.   32.   26.   16.   40.
 24

In [28]:
ages.shape


(714,)

In [29]:

ages.dtype

dtype('float64')

In [30]:

ages.size

714

In [9]:
fares = df['Fare'].to_numpy()
print(fares)

[  7.25    71.2833   7.925   53.1      8.05     8.4583  51.8625  21.075
  11.1333  30.0708  16.7     26.55     8.05    31.275    7.8542  16.
  29.125   13.      18.       7.225   26.      13.       8.0292  35.5
  21.075   31.3875   7.225  263.       7.8792   7.8958  27.7208 146.5208
   7.75    10.5     82.1708  52.       7.2292   8.05    18.      11.2417
   9.475   21.       7.8958  41.5792   7.8792   8.05    15.5      7.75
  21.6792  17.8     39.6875   7.8     76.7292  26.      61.9792  35.5
  10.5      7.2292  27.75    46.9      7.2292  80.      83.475   27.9
  27.7208  15.2458  10.5      8.1583   7.925    8.6625  10.5     46.9
  73.5     14.4542  56.4958   7.65     7.8958   8.05    29.      12.475
   9.       9.5      7.7875  47.1     10.5     15.85    34.375    8.05
 263.       8.05     8.05     7.8542  61.175   20.575    7.25     8.05
  34.6542  63.3583  23.      26.       7.8958   7.8958  77.2875   8.6542
   7.925    7.8958   7.65     7.775    7.8958  24.15    52.      14.4542
  

In [50]:
rupee = fares *86
print(rupee)

[  623.5     6130.3638   681.55    4566.6      692.3      727.4138
  4460.175   1812.45     957.4638  2586.0888  1436.2     2283.3
   692.3     2689.65     675.4612  1376.      2504.75    1118.
  1548.       621.35    2236.      1118.       690.5112  3053.
  1812.45    2699.325    621.35   22618.       677.6112   679.0388
  2383.9888 12600.7888   666.5      903.      7066.6888  4472.
   621.7112   692.3     1548.       966.7862   814.85    1806.
   679.0388  3575.8112   677.6112   692.3     1333.       666.5
  1864.4112  1530.8     3413.125    670.8     6598.7112  2236.
  5330.2112  3053.       903.       621.7112  2386.5     4033.4
   621.7112  6880.      7178.85    2399.4     2383.9888  1311.1388
   903.       701.6138   681.55     744.975    903.      4033.4
  6321.      1243.0612  4858.6388   657.9      679.0388   692.3
  2494.      1072.85     774.       817.       669.725   4050.6
   903.      1363.1     2956.25     692.3    22618.       692.3
   692.3      675.4612  5261.05    1

In [49]:
new=fares *1.10
print(new)

[  7.975    78.41163   8.7175   58.41      8.855     9.30413  57.04875
  23.1825   12.24663  33.07788  18.37     29.205     8.855    34.4025
   8.63962  17.6      32.0375   14.3      19.8       7.9475   28.6
  14.3       8.83212  39.05     23.1825   34.52625   7.9475  289.3
   8.66712   8.68538  30.49288 161.17288   8.525    11.55     90.38788
  57.2       7.95212   8.855    19.8      12.36587  10.4225   23.1
   8.68538  45.73712   8.66712   8.855    17.05      8.525    23.84712
  19.58     43.65625   8.58     84.40212  28.6      68.17712  39.05
  11.55      7.95212  30.525    51.59      7.95212  88.       91.8225
  30.69     30.49288  16.77038  11.55      8.97413   8.7175    9.52875
  11.55     51.59     80.85     15.89962  62.14538   8.415     8.68538
   8.855    31.9      13.7225    9.9      10.45      8.56625  51.81
  11.55     17.435    37.8125    8.855   289.3       8.855     8.855
   8.63962  67.2925   22.6325    7.975     8.855    38.11962  69.69413
  25.3      28.6       8.685

In [10]:
np.mean(ages)


np.float64(29.69911764705882)

In [12]:
t=np.mean(ages)
print(t)

29.69911764705882


In [11]:
np.median(ages)

np.float64(28.0)

In [13]:
t=np.median(ages)
print(t)

28.0


In [14]:
np.min(ages)


np.float64(0.42)

In [15]:
t=np.min(ages)
print(t)

0.42


In [16]:
t=np.max(ages)
print(t)


80.0


In [17]:

t=np.min(fares)
print(t)


0.0


In [18]:
t=np.max(fares)
print(t)

512.3292


In [19]:
t=np.std(ages)
print(t)

14.516321150817316


In [21]:
t=np.var(ages)
print(t)

210.72357975366617


In [22]:
t=np.percentile(ages, 25)
print(t)


20.125


In [23]:
t=np.percentile(ages, 50)
print(t)


28.0


In [24]:
t=np.percentile(ages, 75)
print(t)

38.0


In [26]:

t=np.sum(df['Survived'])
print(t)

342


In [31]:
np.quantile(ages, 0.25)


np.float64(20.125)

In [32]:
t=np.quantile(ages, 0.5)
print(t)

28.0


In [34]:
t=np.quantile(ages, 0.75)
print(t)

38.0


In [35]:
np.square(ages)


array([4.84000e+02, 1.44400e+03, 6.76000e+02, 1.22500e+03, 1.22500e+03,
       2.91600e+03, 4.00000e+00, 7.29000e+02, 1.96000e+02, 1.60000e+01,
       3.36400e+03, 4.00000e+02, 1.52100e+03, 1.96000e+02, 3.02500e+03,
       4.00000e+00, 9.61000e+02, 1.22500e+03, 1.15600e+03, 2.25000e+02,
       7.84000e+02, 6.40000e+01, 1.44400e+03, 3.61000e+02, 1.60000e+03,
       4.35600e+03, 7.84000e+02, 1.76400e+03, 4.41000e+02, 3.24000e+02,
       1.96000e+02, 1.60000e+03, 7.29000e+02, 9.00000e+00, 3.61000e+02,
       3.24000e+02, 4.90000e+01, 4.41000e+02, 2.40100e+03, 8.41000e+02,
       4.22500e+03, 4.41000e+02, 8.12250e+02, 2.50000e+01, 1.21000e+02,
       4.84000e+02, 1.44400e+03, 2.02500e+03, 1.60000e+01, 8.41000e+02,
       3.61000e+02, 2.89000e+02, 6.76000e+02, 1.02400e+03, 2.56000e+02,
       4.41000e+02, 6.76000e+02, 1.02400e+03, 6.25000e+02, 6.88900e-01,
       9.00000e+02, 4.84000e+02, 8.41000e+02, 7.84000e+02, 2.89000e+02,
       1.08900e+03, 2.56000e+02, 5.29000e+02, 5.76000e+02, 8.410

In [36]:

np.sqrt(ages)

array([4.69041576, 6.164414  , 5.09901951, 5.91607978, 5.91607978,
       7.34846923, 1.41421356, 5.19615242, 3.74165739, 2.        ,
       7.61577311, 4.47213595, 6.244998  , 3.74165739, 7.41619849,
       1.41421356, 5.56776436, 5.91607978, 5.83095189, 3.87298335,
       5.29150262, 2.82842712, 6.164414  , 4.35889894, 6.32455532,
       8.1240384 , 5.29150262, 6.4807407 , 4.58257569, 4.24264069,
       3.74165739, 6.32455532, 5.19615242, 1.73205081, 4.35889894,
       4.24264069, 2.64575131, 4.58257569, 7.        , 5.38516481,
       8.06225775, 4.58257569, 5.33853913, 2.23606798, 3.31662479,
       4.69041576, 6.164414  , 6.70820393, 2.        , 5.38516481,
       4.35889894, 4.12310563, 5.09901951, 5.65685425, 4.        ,
       4.58257569, 5.09901951, 5.65685425, 5.        , 0.91104336,
       5.47722558, 4.69041576, 5.38516481, 5.29150262, 4.12310563,
       5.74456265, 4.        , 4.79583152, 4.89897949, 5.38516481,
       4.47213595, 6.78232998, 5.09901951, 7.68114575, 8.42614

In [37]:
np.abs(ages)

array([22.  , 38.  , 26.  , 35.  , 35.  , 54.  ,  2.  , 27.  , 14.  ,
        4.  , 58.  , 20.  , 39.  , 14.  , 55.  ,  2.  , 31.  , 35.  ,
       34.  , 15.  , 28.  ,  8.  , 38.  , 19.  , 40.  , 66.  , 28.  ,
       42.  , 21.  , 18.  , 14.  , 40.  , 27.  ,  3.  , 19.  , 18.  ,
        7.  , 21.  , 49.  , 29.  , 65.  , 21.  , 28.5 ,  5.  , 11.  ,
       22.  , 38.  , 45.  ,  4.  , 29.  , 19.  , 17.  , 26.  , 32.  ,
       16.  , 21.  , 26.  , 32.  , 25.  ,  0.83, 30.  , 22.  , 29.  ,
       28.  , 17.  , 33.  , 16.  , 23.  , 24.  , 29.  , 20.  , 46.  ,
       26.  , 59.  , 71.  , 23.  , 34.  , 34.  , 28.  , 21.  , 33.  ,
       37.  , 28.  , 21.  , 38.  , 47.  , 14.5 , 22.  , 20.  , 17.  ,
       21.  , 70.5 , 29.  , 24.  ,  2.  , 21.  , 32.5 , 32.5 , 54.  ,
       12.  , 24.  , 45.  , 33.  , 20.  , 47.  , 29.  , 25.  , 23.  ,
       19.  , 37.  , 16.  , 24.  , 22.  , 24.  , 19.  , 18.  , 19.  ,
       27.  ,  9.  , 36.5 , 42.  , 51.  , 22.  , 55.5 , 40.5 , 51.  ,
       16.  , 30.  ,

In [39]:
np.sin(ages)


array([-0.00885131,  0.29636858,  0.76255845, -0.42818267, -0.42818267,
       -0.55878905,  0.90929743,  0.95637593,  0.99060736, -0.7568025 ,
        0.99287265,  0.91294525,  0.96379539,  0.99060736, -0.99975517,
        0.90929743, -0.40403765, -0.42818267,  0.52908269,  0.65028784,
        0.27090579,  0.98935825,  0.29636858,  0.14987721,  0.74511316,
       -0.02655115,  0.27090579, -0.91652155,  0.83665564, -0.75098725,
        0.99060736,  0.74511316,  0.95637593,  0.14112001,  0.14987721,
       -0.75098725,  0.6569866 ,  0.83665564, -0.95375265, -0.66363388,
        0.82682868,  0.83665564, -0.22375564, -0.95892427, -0.99999021,
       -0.00885131,  0.29636858,  0.85090352, -0.7568025 , -0.66363388,
        0.14987721, -0.96139749,  0.76255845,  0.55142668, -0.28790332,
        0.83665564,  0.76255845,  0.55142668, -0.13235175,  0.73793137,
       -0.98803162, -0.00885131, -0.66363388,  0.27090579, -0.96139749,
        0.99991186, -0.28790332, -0.8462204 , -0.90557836, -0.66

In [40]:
np.cos(ages)


array([-0.99996083,  0.95507364,  0.64691932, -0.90369221, -0.90369221,
       -0.82930983, -0.41614684, -0.29213881,  0.13673722, -0.65364362,
        0.11918014,  0.40808206,  0.26664293,  0.13673722,  0.02212676,
       -0.41614684,  0.91474236, -0.90369221, -0.84857027, -0.75968791,
       -0.96260587, -0.14550003,  0.95507364,  0.98870462, -0.66693806,
       -0.99964746, -0.96260587, -0.39998531, -0.54772926,  0.66031671,
        0.13673722, -0.66693806, -0.29213881, -0.9899925 ,  0.98870462,
        0.66031671,  0.75390225, -0.54772926,  0.30059254, -0.74805753,
       -0.56245385, -0.54772926, -0.97464528,  0.28366219,  0.0044257 ,
       -0.99996083,  0.95507364,  0.52532199, -0.65364362, -0.74805753,
        0.98870462, -0.27516334,  0.64691932,  0.83422336, -0.95765948,
       -0.54772926,  0.64691932,  0.83422336,  0.99120281,  0.67487576,
        0.15425145, -0.99996083, -0.74805753, -0.96260587, -0.27516334,
       -0.01327675, -0.95765948, -0.53283302,  0.42417901, -0.74

In [41]:
np.tan(ages)

array([ 8.85165604e-03,  3.10309661e-01,  1.17875355e+00,  4.73814720e-01,
        4.73814720e-01,  6.73800101e-01, -2.18503986e+00, -3.27370380e+00,
        7.24460662e+00,  1.15782128e+00,  8.33085685e+00,  2.23716094e+00,
        3.61455441e+00,  7.24460662e+00, -4.51830879e+01, -2.18503986e+00,
       -4.41695568e-01,  4.73814720e-01, -6.23498963e-01, -8.55993401e-01,
       -2.81429605e-01, -6.79971146e+00,  3.10309661e-01,  1.51589471e-01,
       -1.11721493e+00,  2.65605178e-02, -2.81429605e-01,  2.29138799e+00,
       -1.52749853e+00, -1.13731371e+00,  7.24460662e+00, -1.11721493e+00,
       -3.27370380e+00, -1.42546543e-01,  1.51589471e-01, -1.13731371e+00,
        8.71447983e-01, -1.52749853e+00, -3.17290855e+00,  8.87142844e-01,
       -1.47003826e+00, -1.52749853e+00,  2.29576489e-01, -3.38051501e+00,
       -2.25950846e+02,  8.85165604e-03,  3.10309661e-01,  1.61977519e+00,
        1.15782128e+00,  8.87142844e-01,  1.51589471e-01,  3.49391565e+00,
        1.17875355e+00,  

In [42]:
np.prod(ages[:5])

np.float64(26626600.0)

In [47]:
r=np.histogram(fares, bins=10)
print(r)

(array([732, 106,  31,   2,  11,   6,   0,   0,   0,   3]), array([  0.     ,  51.23292, 102.46584, 153.69876, 204.93168, 256.1646 ,
       307.39752, 358.63044, 409.86336, 461.09628, 512.3292 ]))


In [48]:
a=ages+5
print(a)

[27.   43.   31.   40.   40.   59.    7.   32.   19.    9.   63.   25.
 44.   19.   60.    7.   36.   40.   39.   20.   33.   13.   43.   24.
 45.   71.   33.   47.   26.   23.   19.   45.   32.    8.   24.   23.
 12.   26.   54.   34.   70.   26.   33.5  10.   16.   27.   43.   50.
  9.   34.   24.   22.   31.   37.   21.   26.   31.   37.   30.    5.83
 35.   27.   34.   33.   22.   38.   21.   28.   29.   34.   25.   51.
 31.   64.   76.   28.   39.   39.   33.   26.   38.   42.   33.   26.
 43.   52.   19.5  27.   25.   22.   26.   75.5  34.   29.    7.   26.
 37.5  37.5  59.   17.   29.   50.   38.   25.   52.   34.   30.   28.
 24.   42.   21.   29.   27.   29.   24.   23.   24.   32.   14.   41.5
 47.   56.   27.   60.5  45.5  56.   21.   35.   49.   45.   31.   22.
  6.   14.   50.   33.   66.    9.    6.   26.   61.   23.   55.   35.
 41.   14.    6.    9.   50.   45.   41.   37.   24.   24.    8.   49.
 63.   47.   29.   33.   39.   50.5  23.    7.   37.   31.   21.   45.
 29